### PR TITLE
Copy QIIME 2 Wiki over to Sphinx docs build.

### PR DESCRIPTION
**Pull request by jakereps**
Resolves project board item "Port wiki docs"

Customizable, I let it sit at a depth of 2, but can just be headers like the Wiki is by just changing the  `toctree` on `index.rst` to `:maxdepth: 1` if needed.

### CODE REVIEW

**Comment by jakereps** [comment]
Since this one was more than just a style change I'll hold off merging until there is a review.

**Comment by thermokarst** [comment]
Can you remove the bullet glyphs in the sidebar:

image

**Comment by jakereps** [comment]
Got those removed, @thermokarst 👍

**Review by thermokarst — APPROVED** [review]
Thanks @jakereps!

**Pull request merged**
